// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddFolder(arg1:string,arg2:string):Promise<void>;

export function CaptionImage(arg1:string):Promise<Array<string>>;

export function GetFolders():Promise<Array<main.FolderData>>;

export function GetImageByFolders(arg1:Array<string>):Promise<Array<main.ImageData>>;

export function GetImages():Promise<Array<main.ImageData>>;

export function Greet(arg1:string):Promise<string>;

export function QueueAllUntaggedForTagging():Promise<void>;

export function RemoveFolder(arg1:string):Promise<void>;

export function ScanFolder():Promise<void>;

export function ScanFolders(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function TagAllUntagged():Promise<void>;

export function UnTaggedImages():Promise<Array<main.ImageData>>;
