// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1, arg2) {
  return window['go']['main']['App']['AddFolder'](arg1, arg2);
}

export function CaptionImage(arg1) {
  return window['go']['main']['App']['CaptionImage'](arg1);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetImageByFolders(arg1) {
  return window['go']['main']['App']['GetImageByFolders'](arg1);
}

export function GetImages() {
  return window['go']['main']['App']['GetImages']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function ScanFolder() {
  return window['go']['main']['App']['ScanFolder']();
}

export function ScanFolders(arg1) {
  return window['go']['main']['App']['ScanFolders'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function UnTaggedImages() {
  return window['go']['main']['App']['UnTaggedImages']();
}
