// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1, arg2) {
  return window['go']['main']['App']['AddFolder'](arg1, arg2);
}

export function CaptionImage(arg1) {
  return window['go']['main']['App']['CaptionImage'](arg1);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetImages() {
  return window['go']['main']['App']['GetImages']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function ScanFolders() {
  return window['go']['main']['App']['ScanFolders']();
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}
